### ISSUE TITLE
insufficient memory for the Java Runtime Environment to continue.

### ISSUE THREAD

**Issue by mhabsaoui** [lappsgrid-services/brandeis-dkprocore-service#4]
Hi,

I just wanted to report an error about "JRE memory" that occurs often enough (not only in dkpro it seems) to be discussed in an issue here.

![image](https://cloud.githubusercontent.com/assets/18755135/26784088/fe3649f8-49fb-11e7-8bc9-6a351f980396.png)

![image](https://cloud.githubusercontent.com/assets/18755135/26784153/4df10032-49fc-11e7-862e-89c9132cf387.png)

![image](https://cloud.githubusercontent.com/assets/18755135/26784377/8b1612f8-49fd-11e7-97ec-d03a8b14bb4d.png)

As you can see, it happens on the DKPro Stanford Tagger (it happens also on others components), with insufficient memory for the Java Runtime Environment to continue :/

Is there anything i can do to avoid such annoying miscellanous (rise the JVM/JRE memory size) ?? 

Thanks for support 👍

**Comment by ksuderman** [comment]
Are you running the DKPro tools in a Docker container (Galaxy Appliance)?  It looks like Tomcat has not been allocated enough memory.  I see our default [Tomcat Docker image](https://github.com/lappsgrid-incubator/docker-tomcat) only allocates 1G of memory for the JVM which isn't nearly enough.

If you are using our Tomcat Docker image you can try the following as a work around:

1. Create a file named setenv.sh containing:

```bash
JAVA_OPTS="-Xmx4g -Djava.awt.headless=true"
```

2. In the **Dockerfile** for the DKPro container copy the setenv.sh file to `/usr/share/tomcat7/bin`.  

You may have to experiment with the amount memory allocated.  On our production server I have this set to 48G (out of 64G).

*[edit]*
Thanks for using the Language Applications Grid!

**Comment by ksuderman** [comment]
@marcverhagen You may want to check the memory allocated to Tomcat on the Brandeis server as well.

**Comment by keighrim** [comment]
We're also allocating 48g here at Brandeis 
```
$ cat setenv.sh
CATALINA_OPTS="-Xmx48g -XX:PermSize=256m -XX:MaxPermSize=1024m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
```

**Comment by mhabsaoui** [comment]
Thanks for your fast feedback :+1: 

Ok i'll test and let you know what...  

As i had also the 'Java heap space', i suppose it's also related to java_opts... 
![image](https://user-images.githubusercontent.com/18755135/26875780-aa77d5be-4b83-11e7-8d72-863cee2235db.png)


BTW, just wondering : 
- why do you use a lappsgrid/tomcat7:1.1.0  'custom builded' version of tomcat (https://github.com/lappsgrid-incubator/docker-tomcat/blob/master/Dockerfile) instead of official and latest (8 or 9 instead of 7) docker image of Tomcat ?

- Is it possible to add an environt. variable in dockerfile of Tomcat container (e.g.  ENV JAVA_OPTS="-Xmx4g -Djava.awt.headless=true" ) ?

- Is it possible you upload the latest versions of WAR archives for 'KDPro + Gate + Lingpipe + Stanford  + Apache OpenNLP ' NLP Suites which are available on http://galaxy.lappsgrid.org/ ?

Thanks.

**Comment by ksuderman** [comment]
In response to your questions:

1. All of our Docker images are based on the same Ubuntu base image so they all have a consistent set of packages installed.  We are still using Tomcat 7 since at least one of the programs we use is not compatible with later Tomcat versions. However, for the appliance images we should probably investigate using a newer Tomcat.
1. Do you mean a parameter that is set when building the image or when launching a container?  I see that V3 of the docker-compose file format now has much better environment handling so something might be possible.  I've opened lappsgrid-incubator/docker-tomcat#2 to track this.

    Also, if I recall correctly Tomcat overwrites the JAVA_OPTS variable, it does not pick it up from the parent environment.  So JAVA_OPTS has to be set in Tomcat's setenv.sh script.
1. The Gate, Lingpipe, and Stanford suites are available from http://downloads.lappsgrid.org  

    @marcverhagen @keighrim could you ensure the Brandeis services are uploaded there as well?  Where *there* is /var/lib/downloads on our proxy server.

**Comment by mhabsaoui** [comment]
I have raised to 12g (out of 16G on our integration server), it seems the exceptions are gone and it works.

@ksuderman  Should i also add the options from Brandeis node in setenv.sh?

> CATALINA_OPTS="-Xmx8g -XX:PermSize=256m -XX:MaxPermSize=1024m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"


PS: 

> The Gate, Lingpipe, and Stanford suites are available from http://downloads.lappsgrid.org

Can you **please** upload also your DKPro release ?

Thanks.

**Comment by ksuderman** [comment]
@mhabsaoui It depends on what version of Java you are using.  The Perm* options are obsolete in Java 8 so will be ignored.  You can set the -XX:HeapDump* options if you want Java to dump the heap when it runs out of memory.  This can be useful when trying to track down memory leaks, but I tend to leave out those options until I need them.

@marcverhagen and/or @keighrim will upload the DKPro tools as soon as they can.

Thanks for using the LAPPS Grid!
