### ISSUE TITLE
DKPro OpenNLP  SAXParseException : Trying to serialize non-XML 1.0 character

### ISSUE THREAD

**Issue by mhabsaoui** [lappsgrid-services/brandeis-dkprocore-service#6]
Hi, 
DKPro OpenNLP works with simple text file. 
It seems with 'complex' text file it trrigers  a new error 'org.xml.sax.SAXParseException; Trying to serialize non-XML 1.0 character: '. 

Did you experienced the same somehow on any test ? This error is text file content related ?

`dkpro_1     | log4j:WARN No appenders could be found for logger (org.apache.commons.discovery.resource.DiscoverResources).
dkpro_1     | log4j:WARN Please initialize the log4j system properly.
dkpro_1     | log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
dkpro_1     | SLF4J: Class path contains multiple SLF4J bindings.
dkpro_1     | SLF4J: Found binding in [jar:file:/var/lib/tomcat7/webapps/DkproServices%231.7.0/WEB-INF/lib/all-2.3.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
dkpro_1     | SLF4J: Found binding in [jar:file:/var/lib/tomcat7/webapps/DkproServices%231.7.0/WEB-INF/lib/logback-classic-1.0.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
dkpro_1     | SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
dkpro_1     | SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
dkpro_1     | StanfordNlpPOSTagger Init...
dkpro_1     | StanfordParser Init...
dkpro_1     | OpenNlpNamedEntityRecognizer Init...
dkpro_1     | OpenNlpTokenizer Init...
dkpro_1     | OpenNlpPOSTagger Init...
dkpro_1     | StanfordNlpTokenizer Init...
dkpro_1     | StanfordCoreferenceResolver Init...
dkpro_1     | OpenNlpSplitter Init...
dkpro_1     | OpenNlpParser Init...
dkpro_1     | StanfordNlpSplitter Init...
dkpro_1     | StanfordNamedEntityRecognizer Init...
dkpro_1     | org.xml.sax.SAXParseException; Trying to serialize non-XML 1.0 character: 
                                                                                        , 0xc at offset 0 in string starting with 
                                                                                                                                  Data Sciences: From First-Order Logic to the Web
dkpro_1     | Inaugural lecture given on Thursday 8 March 2012
dkpro_1     | S
dkpro_1     | 	at org.apache.uima.util.XMLSerializer$CharacterValidatingContentHandler.checkForInvalidXmlChars(XMLSerializer.java:348)
dkpro_1     | 	at org.apache.uima.util.XMLSerializer$CharacterValidatingContentHandler.startElement(XMLSerializer.java:249)
dkpro_1     | 	at org.apache.uima.cas.impl.XmiCasSerializer$XmiCasDocSerializer.startElement(XmiCasSerializer.java:992)
dkpro_1     | 	at org.apache.uima.cas.impl.XmiCasSerializer$XmiCasDocSerializer.encodeFS(XmiCasSerializer.java:743)
dkpro_1     | 	at org.apache.uima.cas.impl.XmiCasSerializer$XmiCasDocSerializer.encodeIndexed(XmiCasSerializer.java:692)
dkpro_1     | 	at org.apache.uima.cas.impl.XmiCasSerializer$XmiCasDocSerializer.serialize(XmiCasSerializer.java:268)
dkpro_1     | 	at org.apache.uima.cas.impl.XmiCasSerializer$XmiCasDocSerializer.access$700(XmiCasSerializer.java:108)
dkpro_1     | 	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:1551)
dkpro_1     | 	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:1616)
dkpro_1     | 	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:1567)
dkpro_1     | 	at org.apache.uima.util.XmlCasSerializer.serialize(XmlCasSerializer.java:52)
dkpro_1     | 	at edu.brandeis.cs.uima.dkpro.AbstractDkProService.uimaDkProXml(AbstractDkProService.java:54)
dkpro_1     | 	at edu.brandeis.cs.uima.dkpro.OpenNlpSplitter.execute(OpenNlpSplitter.java:32)
dkpro_1     | 	at edu.brandeis.cs.uima.AbstractWebService.execute(AbstractWebService.java:73)
dkpro_1     | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dkpro_1     | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
dkpro_1     | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dkpro_1     | 	at java.lang.reflect.Method.invoke(Method.java:606)
dkpro_1     | 	at jp.go.nict.langrid.servicecontainer.decorator.ServiceInvoker.invoke(ServiceInvoker.java:39)
dkpro_1     | 	at jp.go.nict.langrid.servicecontainer.decorator.FirstDecoratorChain.next(FirstDecoratorChain.java:49)
dkpro_1     | 	at jp.go.nict.langrid.servicecontainer.handler.ServiceInvocationHandler.invoke(ServiceInvocationHandler.java:29)
dkpro_1     | 	at com.sun.proxy.$Proxy8.execute(Unknown Source)
dkpro_1     | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dkpro_1     | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
dkpro_1     | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
dkpro_1     | 	at java.lang.reflect.Method.invoke(Method.java:606)
dkpro_1     | 	at org.apache.axis.providers.java.RPCProvider.invokeMethod(RPCProvider.java:397)
dkpro_1     | 	at org.apache.axis.providers.java.RPCProvider.processMessage(RPCProvider.java:186)
dkpro_1     | 	at jp.go.nict.langrid.servicecontainer.handler.axis.SGJavaProvider.processMessage(SGJavaProvider.java:163)
dkpro_1     | 	at org.apache.axis.providers.java.JavaProvider.invoke(JavaProvider.java:323)
dkpro_1     | 	at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
dkpro_1     | 	at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
dkpro_1     | 	at org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
dkpro_1     | 	at org.apache.axis.handlers.soap.SOAPService.invoke(SOAPService.java:454)
dkpro_1     | 	at org.apache.axis.server.AxisServer.invoke(AxisServer.java:281)
dkpro_1     | 	at org.apache.axis.transport.http.AxisServlet.doPost(AxisServlet.java:699)
dkpro_1     | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
dkpro_1     | 	at org.apache.axis.transport.http.AxisServletBase.service(AxisServletBase.java:327)
dkpro_1     | 	at jp.go.nict.langrid.servicecontainer.handler.axis.SGAxisServlet.service(SGAxisServlet.java:169)
dkpro_1     | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
dkpro_1     | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
dkpro_1     | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
dkpro_1     | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
dkpro_1     | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
dkpro_1     | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
dkpro_1     | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
dkpro_1     | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
dkpro_1     | 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
dkpro_1     | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
dkpro_1     | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
dkpro_1     | 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
dkpro_1     | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
dkpro_1     | 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
dkpro_1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
dkpro_1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
dkpro_1     | 	at java.lang.Thread.run(Thread.java:745)
`

Thanks.

**Comment by reckart** [comment]
@mhabsaoui XML does not support all Unicode characters. I assume you'd also hit that problem with GATE components when reading/writing to GATE XML. 

The best way would probably be that you clean up your documents and remove invalid XML characters from them before processing. See the [XML spec](https://www.w3.org/TR/xml/#charsets) for which characters are valid.

As far as I remember, this has been discussed on the UIMA mailing list several times. You could ask there again or try digging up the past threads e.g. https://lists.apache.org/list.html?dev@uima.apache.org:lte=10y:illegal%20xml

Another alternative could be to store the UIMA CASes using a binary format, e.g. using the BinaryCasReader/BinaryCasWriter from DKPro Core.

**Comment by mhabsaoui** [comment]
> The best way would probably be that you clean up your documents and remove invalid XML characters from them before processing. See the XML spec for which characters are valid.

Perfect answer, we were thinking here the same thing :) 

Thanks a lot.
